name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Set up environment variables
        run: |
          echo "MONGODB_URI=${{ secrets.MONGODB_URI }}" >> .env  # Usamos la URI remota de Atlas
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env

      - name: Build the project
        run: npm run build

      - name: Run unit tests
        run: npm run test
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }} # Utiliza el secreto para la conexión remota
          JWT_SECRET: ${{ secrets.JWT_SECRET }}

      - name: Start the app
        run: npm run start &
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }} # URI remota
          JWT_SECRET: ${{ secrets.JWT_SECRET }}

      - name: Run e2e tests
        run: npm run test:e2e
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }} # URI remota
          JWT_SECRET: ${{ secrets.JWT_SECRET }}

      - name: Stop app
        run: kill $(jobs -p) || true
